language: node_js

node_js:
  - 10
  - node

cache: npm

script:
  - npm install
  - npm run test
  - npm run coverage
  - npm run lint

notifications:
  email:
    recipients:
      - avdayan@bgu.ac.il
    on_failure: always
